<a href="https://colab.research.google.com/github/JarekMaleszyk/data-science-project-sandbox/blob/main/numpy_advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [117]:
import numpy as np
import pandas as pd

In [118]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv')
df.reset_index(inplace=True)
df.head()

index  longitude  latitude  housing_median_age  total_rooms  \
0      0    -122.05     37.37                27.0       3885.0   
1      1    -118.30     34.26                43.0       1510.0   
2      2    -117.81     33.78                27.0       3589.0   
3      3    -118.36     33.82                28.0         67.0   
4      4    -119.67     36.33                19.0       1241.0   

   total_bedrooms  population  households  median_income  median_house_value  
0           661.0      1537.0       606.0         6.6085            344700.0  
1           310.0       809.0       277.0         3.5990            176500.0  
2           507.0      1484.0       495.0         5.7934            270500.0  
3            15.0        49.0        11.0         6.1359            330000.0  
4           244.0       850.0       237.0         2.9375             81700.0

In [119]:
df.at[2, "longitude"]

-117.81

In [120]:
df.iat[2, 1]

-117.81

In [121]:
a = np.random.random((5,6,7,1,2,3))
b = np.random.random((5,1,7,5,1,1))

In [122]:
print(a.shape)
print(b.shape)

(5, 6, 7, 1, 2, 3)
(5, 1, 7, 5, 1, 1)


In [123]:
print(a + b)

[[[[[[0.44217175 0.51397067 0.49854074]
     [0.51334338 0.83421773 0.27839037]]

    [[0.95407785 1.02587676 1.01044684]
     [1.02524948 1.34612383 0.79029647]]

    [[1.07791205 1.14971097 1.13428104]
     [1.14908368 1.46995803 0.91413067]]

    [[0.90043456 0.97223348 0.95680355]
     [0.97160619 1.29248054 0.73665318]]

    [[1.37252898 1.44432789 1.42889796]
     [1.44370061 1.76457496 1.20874759]]]


   [[[1.81313331 1.70910886 1.70084031]
     [1.12618911 0.88535786 1.16211045]]

    [[1.68655408 1.58252964 1.57426108]
     [0.99960989 0.75877864 1.03553123]]

    [[1.58532074 1.4812963  1.47302774]
     [0.89837655 0.65754529 0.93429789]]

    [[1.86478243 1.76075799 1.75248943]
     [1.17783824 0.93700699 1.21375958]]

    [[0.99306567 0.88904122 0.88077267]
     [0.30612147 0.06529022 0.34204281]]]


   [[[1.14502687 1.61898154 1.79642692]
     [1.21070411 1.7665825  1.67995162]]

    [[0.27688293 0.75083761 0.92828298]
     [0.34256017 0.89843856 0.81180768]]

    [[0.2772

In [124]:
try:
  a = np.random.random((5,6,7,1,2,3))
  b = np.random.random((5,2,7,5,1,1))
  print(a + b)
except ValueError:
  print(f"Operands could not be broadcast together with shapes {a.shape} {b.shape}")
except Exception as e:
  print(e)
else:
  pass
finally:
  pass

Operands could not be broadcast together with shapes (5, 6, 7, 1, 2, 3) (5, 2, 7, 5, 1, 1)


In [125]:
ma = np.array( [[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[11,12,13],
                [14,15,16],
                [17,18,19]]
                ])
print(ma.shape)
print(ma[0:2, 0:2, 0:1])

(2, 3, 3)
[[[ 1]
  [ 4]]

 [[11]
  [14]]]


In [126]:
print(ma[:, 0, 0, np.newaxis])
print(ma[np.newaxis, :, 0, 0])

[[ 1]
 [11]]
[[ 1 11]]


In [127]:
print(ma[:, [True, True, False]])

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [128]:
arr = np.arange(10, 300, 5.2, dtype=float)
np.random.shuffle(arr)
print(arr)

[186.8 290.8 197.2 275.2 264.8 218.  129.6 280.4  82.8 103.6 212.8  30.8
 202.4  51.6 296.   25.6 134.8 285.6 238.8 145.2  72.4 124.4  10.   77.6
 114.  223.2  56.8  88.   15.2  36.  181.6 119.2  62.  228.4 166.   93.2
 270.  160.8 140.  155.6 259.6  20.4 108.8 150.4 249.2 176.4 207.6 244.
 171.2  67.2  98.4 233.6  41.2  46.4 254.4 192. ]


In [129]:
# arr.sort()

In [131]:
print(np.argmin(arr))
print(np.argmax(arr))

22
14


In [132]:
zrr = np.zeros_like(arr)
print(zrr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]


In [140]:
np.where[arr > 88., arr, arr]

TypeError: 'numpy._ArrayFunctionDispatcher' object is not subscriptable

In [141]:
arr.shape

(56,)

In [146]:
arr[arr > 88]

array([186.8, 290.8, 197.2, 275.2, 264.8, 218. , 129.6, 280.4, 103.6,
       212.8, 202.4, 296. , 134.8, 285.6, 238.8, 145.2, 124.4, 114. ,
       223.2, 181.6, 119.2, 228.4, 166. ,  93.2, 270. , 160.8, 140. ,
       155.6, 259.6, 108.8, 150.4, 249.2, 176.4, 207.6, 244. , 171.2,
        98.4, 233.6, 254.4, 192. ])