<a href="https://colab.research.google.com/github/JarekMaleszyk/data-science-project-sandbox/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
zeros = np.zeros((10,10))
print(zeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [4]:
zeros.shape

(10, 10)

In [9]:
inx = [0,0]
inx[0] = np.random.randint(0,10)
inx[1] = np.random.randint(0,10)
zeros[inx[0],inx[1]] = 1
print(zeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [21]:
ones = np.ones((10,10))
print(ones)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [36]:
# ones[0,:] = 0
# ones[-1,:] = 0
# ones[:,0] = 0
# ones[:,-1] = 0
print(ones.flatten().reshape(20,5))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [48]:
arr = np.arange(10, 300, 5.2, dtype=float)
print(arr)

[ 10.   15.2  20.4  25.6  30.8  36.   41.2  46.4  51.6  56.8  62.   67.2
  72.4  77.6  82.8  88.   93.2  98.4 103.6 108.8 114.  119.2 124.4 129.6
 134.8 140.  145.2 150.4 155.6 160.8 166.  171.2 176.4 181.6 186.8 192.
 197.2 202.4 207.6 212.8 218.  223.2 228.4 233.6 238.8 244.  249.2 254.4
 259.6 264.8 270.  275.2 280.4 285.6 290.8 296. ]


In [55]:
lin = np.linspace(0, 1, 100, endpoint=False, retstep=False, dtype=float, axis=0)
print(lin)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]


In [62]:
char = np.full((15,10), '^', dtype=str)
print(char)

[['^' '^' '^' '^' '^' '^' '^' '^' '^' '^']
 ['^' '^' '^' '^' '^' '^' '^' '^' '^' '^']
 ['^' '^' '^' '^' '^' '^' '^' '^' '^' '^']
 ['^' '^' '^' '^' '^' '^' '^' '^' '^' '^']
 ['^' '^' '^' '^' '^' '^' '^' '^' '^' '^']
 ['^' '^' '^' '^' '^' '^' '^' '^' '^' '^']
 ['^' '^' '^' '^' '^' '^' '^' '^' '^' '^']
 ['^' '^' '^' '^' '^' '^' '^' '^' '^' '^']
 ['^' '^' '^' '^' '^' '^' '^' '^' '^' '^']
 ['^' '^' '^' '^' '^' '^' '^' '^' '^' '^']
 ['^' '^' '^' '^' '^' '^' '^' '^' '^' '^']
 ['^' '^' '^' '^' '^' '^' '^' '^' '^' '^']
 ['^' '^' '^' '^' '^' '^' '^' '^' '^' '^']
 ['^' '^' '^' '^' '^' '^' '^' '^' '^' '^']
 ['^' '^' '^' '^' '^' '^' '^' '^' '^' '^']]


In [63]:
char2 = np.full_like(char, 'v')
print(char2)

[['v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v']
 ['v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v']
 ['v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v']
 ['v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v']
 ['v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v']
 ['v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v']
 ['v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v']
 ['v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v']
 ['v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v']
 ['v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v']
 ['v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v']
 ['v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v']
 ['v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v']
 ['v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v']
 ['v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v' 'v']]


In [82]:
eye = np.eye(10, 13, 3, dtype=int, order='C')
print(eye)

[[0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]]


In [84]:
empty = np.empty((4,4))
print(empty)

[[4.68858532e-310 0.00000000e+000 6.86425401e-310 6.86425393e-310]
 [6.86425393e-310 6.86425393e-310 5.09233928e+246 4.00193173e-322]
 [4.68755366e-310 6.86425467e-310 1.23971686e+224 1.05162885e-153]
 [9.03292329e+271 9.08366793e+223 1.06244660e-153 3.44981369e+175]]


In [97]:
i = np.int64
f = np.float32
c = np.complex64
b = np.bool_
o = np.object_
s = np.string_
u = np.unicode_
v = np.void
print(i, f, c, b, o, s, u, v)
print(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], dtype='int64'))
print(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], dtype='float32'))
print(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], dtype='complex64'))
print(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], dtype='bool_'))
print(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], dtype='object_'))
print(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], dtype='string_'))
print(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], dtype='unicode_'))

<class 'numpy.int64'> <class 'numpy.float32'> <class 'numpy.complex64'> <class 'numpy.bool_'> <class 'numpy.object_'> <class 'numpy.bytes_'> <class 'numpy.str_'> <class 'numpy.void'>
[1 2 3 4 5 6 7 8 9 0]
[1. 2. 3. 4. 5. 6. 7. 8. 9. 0.]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j 8.+0.j 9.+0.j 0.+0.j]
[ True  True  True  True  True  True  True  True  True False]
[1 2 3 4 5 6 7 8 9 0]
[b'1' b'2' b'3' b'4' b'5' b'6' b'7' b'8' b'9' b'0']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '0']


In [127]:
uni = u"Hello word!"
z = [x for x in uni]
arrz = np.array(z)
arrz.dtype

dtype('<U1')

In [142]:
i = np.identity(10, dtype=int)
i *= 50

In [161]:
inx = [0,0]
inx[0] = np.random.randint(0,10)
inx[1] = np.random.randint(0,10)
i[inx[0],inx[1]] += 1
print(i)

[[51  1  0  0  0  0  0  0  0  0]
 [ 0 50  1  0  0  0  0  1  0  0]
 [ 0  0 51  0  0  1  0  2  1  0]
 [ 0  0  0 50  0  0  0  1  0  0]
 [ 0  0  1  0 50  1  0  0  0  0]
 [ 0  0  1  0  1 50  0  0  0  0]
 [ 0  0  0  0  0  1 51  0  0  0]
 [ 0  0  0  0  0  0  0 50  0  0]
 [ 1  0  0  0  0  1  0  0 50  0]
 [ 0  0  0  1  0  0  0  0  0 50]]
