<a href="https://colab.research.google.com/github/JarekMaleszyk/data-science-project-sandbox/blob/main/numpy_advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import numpy as np
import pandas as pd

In [52]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv')
df.reset_index(inplace=True)
df.head()

index  longitude  latitude  housing_median_age  total_rooms  \
0      0    -122.05     37.37                27.0       3885.0   
1      1    -118.30     34.26                43.0       1510.0   
2      2    -117.81     33.78                27.0       3589.0   
3      3    -118.36     33.82                28.0         67.0   
4      4    -119.67     36.33                19.0       1241.0   

   total_bedrooms  population  households  median_income  median_house_value  
0           661.0      1537.0       606.0         6.6085            344700.0  
1           310.0       809.0       277.0         3.5990            176500.0  
2           507.0      1484.0       495.0         5.7934            270500.0  
3            15.0        49.0        11.0         6.1359            330000.0  
4           244.0       850.0       237.0         2.9375             81700.0

In [53]:
df.at[2, "longitude"]

-117.81

In [54]:
df.iat[2, 1]

-117.81

In [55]:
a = np.random.random((5,6,7,1,2,3))
b = np.random.random((5,1,7,5,1,1))

In [56]:
print(a.shape)
print(b.shape)

(5, 6, 7, 1, 2, 3)
(5, 1, 7, 5, 1, 1)


In [57]:
print(a + b)

[[[[[[1.02191573 1.47915475 1.17224161]
     [1.22826789 1.29531738 0.73952144]]

    [[0.7405486  1.19778762 0.89087448]
     [0.94690076 1.01395025 0.45815431]]

    [[0.67154671 1.12878572 0.82187258]
     [0.87789886 0.94494835 0.38915241]]

    [[0.98226578 1.43950479 1.13259166]
     [1.18861793 1.25566742 0.69987149]]

    [[0.5051917  0.96243071 0.65551757]
     [0.71154385 0.77859334 0.2227974 ]]]


   [[[1.11942323 0.44757716 0.73127946]
     [0.24393313 1.0136916  0.57886274]]

    [[1.41222304 0.74037697 1.02407927]
     [0.53673294 1.30649141 0.87166255]]

    [[0.89358301 0.22173693 0.50543923]
     [0.01809291 0.78785138 0.35302252]]

    [[1.13417972 0.46233365 0.74603595]
     [0.25868962 1.02844809 0.59361923]]

    [[1.2774778  0.60563172 0.88933402]
     [0.4019877  1.17174616 0.7369173 ]]]


   [[[0.65280623 1.23211273 1.24185177]
     [1.12178924 1.3068779  0.96943309]]

    [[0.87626206 1.45556855 1.46530759]
     [1.34524507 1.53033373 1.19288892]]

    [[1.2139

In [58]:
try:
  a = np.random.random((5,6,7,1,2,3))
  b = np.random.random((5,2,7,5,1,1))
  print(a + b)
except ValueError:
  print(f"Operands could not be broadcast together with shapes {a.shape} {b.shape}")
except Exception as e:
  print(e)
else:
  pass
finally:
  pass

Operands could not be broadcast together with shapes (5, 6, 7, 1, 2, 3) (5, 2, 7, 5, 1, 1)


In [59]:
ma = np.array( [[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[11,12,13],
                [14,15,16],
                [17,18,19]]
                ])
print(ma.shape)
print(ma[0:2, 0:2, 0:1])

(2, 3, 3)
[[[ 1]
  [ 4]]

 [[11]
  [14]]]


In [60]:
print(ma[:, 0, 0, np.newaxis])
print(ma[np.newaxis, :, 0, 0])

[[ 1]
 [11]]
[[ 1 11]]


In [61]:
print(ma[:, [True, True, False]])

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [62]:
arr = np.arange(10, 300, 5.2, dtype=float)
np.random.shuffle(arr)
print(arr)

[140.  155.6 285.6 186.8 228.4 218.  296.  259.6  25.6  77.6 166.  150.4
 207.6 233.6  46.4 249.2 103.6  72.4  41.2 145.2 212.8 254.4 192.  160.8
 124.4 114.   93.2 275.2 290.8  82.8 202.4  88.  197.2 238.8  10.   51.6
  56.8  20.4  36.   30.8 181.6 119.2 108.8  15.2 171.2 264.8  67.2 244.
 223.2 176.4 280.4  98.4 270.  134.8 129.6  62. ]


In [63]:
# arr.sort()

In [64]:
print(np.argmin(arr))
print(np.argmax(arr))

34
6


In [65]:
zrr = np.zeros_like(arr)
print(zrr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]


In [66]:
arr.__getitem__(slice(0, 10, 2))

array([140. , 285.6, 228.4, 296. ,  25.6])

In [67]:
try:
  np.where[arr > 88., arr, arr]
except TypeError:
  print("numpy._ArrayFunctionDispatcher' object is not subscriptable")
except Exception as e:
  print(e)
else:
  pass
finally:
  pass

numpy._ArrayFunctionDispatcher' object is not subscriptable


In [68]:
arr.shape

(56,)

In [69]:
arr[arr > 88]

array([140. , 155.6, 285.6, 186.8, 228.4, 218. , 296. , 259.6, 166. ,
       150.4, 207.6, 233.6, 249.2, 103.6, 145.2, 212.8, 254.4, 192. ,
       160.8, 124.4, 114. ,  93.2, 275.2, 290.8, 202.4, 197.2, 238.8,
       181.6, 119.2, 108.8, 171.2, 264.8, 244. , 223.2, 176.4, 280.4,
        98.4, 270. , 134.8, 129.6])

In [70]:
!cat /var/log/bootstrap.log | grep adduser -A 4

2023-10-04 02:07:18 URL:http://ftpmaster.internal/ubuntu/pool/main/a/adduser/adduser_3.118ubuntu5_all.deb [155528/155528] -> "/build/chroot//var/cache/apt/archives/partial/adduser_3.118ubuntu5_all.deb" [1]
2023-10-04 02:07:20 URL:http://ftpmaster.internal/ubuntu/pool/main/a/apt/apt_2.4.5_amd64.deb [1379030/1379030] -> "/build/chroot//var/cache/apt/archives/partial/apt_2.4.5_amd64.deb" [1]
2023-10-04 02:07:20 URL:http://ftpmaster.internal/ubuntu/pool/main/b/base-files/base-files_12ubuntu4_amd64.deb [62940/62940] -> "/build/chroot//var/cache/apt/archives/partial/base-files_12ubuntu4_amd64.deb" [1]
2023-10-04 02:07:20 URL:http://ftpmaster.internal/ubuntu/pool/main/b/base-passwd/base-passwd_3.5.52build1_amd64.deb [49100/49100] -> "/build/chroot//var/cache/apt/archives/partial/base-passwd_3.5.52build1_amd64.deb" [1]
2023-10-04 02:07:21 URL:http://ftpmaster.internal/ubuntu/pool/main/b/bash/bash_5.1-6ubuntu1_amd64.deb [768660/768660] -> "/build/chroot//var/cache/apt/archives/partial/bash_5.1-

In [71]:
!pip install pytest ipytest --quiet

In [72]:
import ipytest
ipytest.autoconfig()

In [73]:
def test_add():
  %time
  assert 1 + 1 == 2

In [75]:
import pytest

def test_passes():
    with pytest.raises(Exception) as e_info:
        x = 1 / 0

def test_passes_without_info():
    with pytest.raises(Exception):
        x = 1 / 0

def test_fails():
    with pytest.raises(Exception) as e_info:
        x = 1 / 1

def test_fails_without_info():
    with pytest.raises(Exception):
        x = 1 / 1

# Don't do this. Assertions are caught as exceptions.
def test_passes_but_should_not():
    try:
        x = 1 / 1
        assert False
    except Exception:
        assert True

# Even if the appropriate exception is caught, it is bad style,
# because the test result is less informative
# than it would be with pytest.raises(e)
# (it just says pass or fail.)

def test_passes_but_bad_style():
    try:
        x = 1 / 0
        assert False
    except ZeroDivisionError:
        assert True

def test_fails_but_bad_style():
    try:
        x = 1 / 1
        assert False
    except ZeroDivisionError:
        assert True

In [76]:
%%time
ipytest.run('-vv')

======================================= test session starts ========================================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.5.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content
plugins: typeguard-4.3.0, anyio-3.7.1
collecting ... collected 8 items

t_d1ab5275e1384d91b6b16fc099424f60.py::test_add PASSED                                       [ 12%]
t_d1ab5275e1384d91b6b16fc099424f60.py::test_passes PASSED                                    [ 25%]
t_d1ab5275e1384d91b6b16fc099424f60.py::test_passes_without_info PASSED                       [ 37%]
t_d1ab5275e1384d91b6b16fc099424f60.py::test_fails FAILED                                     [ 50%]
t_d1ab5275e1384d91b6b16fc099424f60.py::test_fails_without_info FAILED                        [ 62%]
t_d1ab5275e1384d91b6b16fc099424f60.py::test_passes_but_should_not PASSED                     [ 75%]
t_d1ab5275e1384d91b6b16fc099424f60.py::test_passes_but_bad_style PASSED                      [ 87%]
t_d1

<ExitCode.TESTS_FAILED: 1>