<a href="https://colab.research.google.com/github/JarekMaleszyk/data-science-project-sandbox/blob/main/numpy_advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [116]:
%pdb
import numpy as np
import pandas as pd

Automatic pdb calling has been turned OFF


In [117]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv')
df.reset_index(inplace=True)
df.head()

index  longitude  latitude  housing_median_age  total_rooms  \
0      0    -122.05     37.37                27.0       3885.0   
1      1    -118.30     34.26                43.0       1510.0   
2      2    -117.81     33.78                27.0       3589.0   
3      3    -118.36     33.82                28.0         67.0   
4      4    -119.67     36.33                19.0       1241.0   

   total_bedrooms  population  households  median_income  median_house_value  
0           661.0      1537.0       606.0         6.6085            344700.0  
1           310.0       809.0       277.0         3.5990            176500.0  
2           507.0      1484.0       495.0         5.7934            270500.0  
3            15.0        49.0        11.0         6.1359            330000.0  
4           244.0       850.0       237.0         2.9375             81700.0

In [118]:
df.at[2, "longitude"]

-117.81

In [119]:
df.iat[2, 1]

-117.81

In [120]:
a = np.random.random((5,6,7,1,2,3))
b = np.random.random((5,1,7,5,1,1))

In [121]:
print(a.shape)
print(b.shape)

(5, 6, 7, 1, 2, 3)
(5, 1, 7, 5, 1, 1)


In [122]:
c = a + b
c.shape

(5, 6, 7, 5, 2, 3)

In [123]:
try:
  a = np.random.random((5,6,7,1,2,3))
  b = np.random.random((5,2,7,5,1,1))
  print(a + b)
except ValueError:
  print(f"Operands could not be broadcast together with shapes {a.shape} {b.shape}")
except Exception as e:
  print(e)
else:
  pass
finally:
  pass

Operands could not be broadcast together with shapes (5, 6, 7, 1, 2, 3) (5, 2, 7, 5, 1, 1)


In [124]:
ma = np.array( [[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[11,12,13],
                [14,15,16],
                [17,18,19]]
                ])
print(ma.shape)
print(ma[0:2, 0:2, 0:1])

(2, 3, 3)
[[[ 1]
  [ 4]]

 [[11]
  [14]]]


In [125]:
print(ma[:, 0, 0, np.newaxis])
print(ma[np.newaxis, :, 0, 0])

[[ 1]
 [11]]
[[ 1 11]]


In [126]:
print(ma[:, [True, True, False]])

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [127]:
arr = np.arange(10, 300, 5.2, dtype=float)
np.random.shuffle(arr)
print(arr)

[181.6 207.6 249.2 280.4  30.8 259.6 285.6 103.6  15.2  77.6 254.4  98.4
 202.4  72.4 134.8  56.8  25.6 160.8  62.  119.2 228.4 129.6 290.8  41.2
 296.  197.2 124.4  46.4 145.2 244.  155.6 114.  140.  264.8 171.2  10.
  88.  150.4  82.8 218.  238.8  36.  233.6 166.  186.8 223.2 192.   20.4
 212.8  93.2  67.2  51.6 275.2 270.  108.8 176.4]


In [128]:
# arr.sort()

In [129]:
print(np.argmin(arr))
print(np.argmax(arr))

35
24


In [130]:
zrr = np.zeros_like(arr)
print(zrr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]


In [131]:
arr.__getitem__(slice(0, 10, 2))

array([181.6, 249.2,  30.8, 285.6,  15.2])

In [132]:
try:
  np.where[arr > 88., arr, arr]
except TypeError:
  print("numpy._ArrayFunctionDispatcher' object is not subscriptable")
except Exception as e:
  print(e)
else:
  pass
finally:
  pass

numpy._ArrayFunctionDispatcher' object is not subscriptable


In [133]:
arr.shape

(56,)

In [134]:
arr[arr > 88]

array([181.6, 207.6, 249.2, 280.4, 259.6, 285.6, 103.6, 254.4,  98.4,
       202.4, 134.8, 160.8, 119.2, 228.4, 129.6, 290.8, 296. , 197.2,
       124.4, 145.2, 244. , 155.6, 114. , 140. , 264.8, 171.2, 150.4,
       218. , 238.8, 233.6, 166. , 186.8, 223.2, 192. , 212.8,  93.2,
       275.2, 270. , 108.8, 176.4])

In [135]:
!cat /var/log/bootstrap.log | grep adduser -A 4

2023-10-04 02:07:18 URL:http://ftpmaster.internal/ubuntu/pool/main/a/adduser/adduser_3.118ubuntu5_all.deb [155528/155528] -> "/build/chroot//var/cache/apt/archives/partial/adduser_3.118ubuntu5_all.deb" [1]
2023-10-04 02:07:20 URL:http://ftpmaster.internal/ubuntu/pool/main/a/apt/apt_2.4.5_amd64.deb [1379030/1379030] -> "/build/chroot//var/cache/apt/archives/partial/apt_2.4.5_amd64.deb" [1]
2023-10-04 02:07:20 URL:http://ftpmaster.internal/ubuntu/pool/main/b/base-files/base-files_12ubuntu4_amd64.deb [62940/62940] -> "/build/chroot//var/cache/apt/archives/partial/base-files_12ubuntu4_amd64.deb" [1]
2023-10-04 02:07:20 URL:http://ftpmaster.internal/ubuntu/pool/main/b/base-passwd/base-passwd_3.5.52build1_amd64.deb [49100/49100] -> "/build/chroot//var/cache/apt/archives/partial/base-passwd_3.5.52build1_amd64.deb" [1]
2023-10-04 02:07:21 URL:http://ftpmaster.internal/ubuntu/pool/main/b/bash/bash_5.1-6ubuntu1_amd64.deb [768660/768660] -> "/build/chroot//var/cache/apt/archives/partial/bash_5.1-

In [136]:
!pip install pytest ipytest --quiet

In [137]:
import ipytest
ipytest.autoconfig(clean=True) #https://pypi.org/project/ipytest/

In [138]:
def test_add():
  %time
  assert 1 + 1 == 2

In [139]:
import pytest

def test_passes():
    with pytest.raises(Exception) as e_info:
        x = 1 / 0

def test_passes_without_info():
    with pytest.raises(Exception):
        x = 1 / 0

# def test_fails():
#     with pytest.raises(Exception) as e_info:
#         x = 1 / 1

# def test_fails_without_info():
#     with pytest.raises(Exception):
#         x = 1 / 1

# Don't do this. Assertions are caught as exceptions.
def test_passes_but_should_not():
    try:
        x = 1 / 1
        assert False
    except Exception:
        assert True

# Even if the appropriate exception is caught, it is bad style,
# because the test result is less informative
# than it would be with pytest.raises(e)
# (it just says pass or fail.)

def test_passes_but_bad_style():
    try:
        x = 1 / 0
        assert False
    except ZeroDivisionError:
        assert True

# def test_fails_but_bad_style():
#     try:
#         x = 1 / 1
#         assert False
#     except ZeroDivisionError:
#         assert True

In [140]:
from functools import cache

@cache
def fibonacci(n: int) -> int:
    if n < 2 :
        return n
    return fibonacci(n - 1) + fibonacci(n - 2) #infinitive recursion

In [141]:
def test_fibonacci():
    assert fibonacci(41) == 165580141

In [142]:
import time
from time import perf_counter, sleep
from functools import wraps
from typing import Callable, Any

def get_time(func: Callable) -> Callable:
    @wraps(func)
    def wrapper(*args, **kwargs) -> Any:
        # Note that timing your code once isn't the most reliable option
        # for timing your code. Look into the timeit module for more accurate
        # timing.
        start_time: float = perf_counter()
        result: Any = func(*args, **kwargs)
        end_time: float = perf_counter()

        print(f'"{func.__name__}()" took {end_time - start_time:.3f} seconds to execute')
        return result

    return wrapper

In [143]:
@get_time
def connect() -> bool:
    print('Connecting...')
    sleep(2)
    print('Connected!')
    return True

@get_time
def fifty_million_loops() -> bool:
    fifty_million: int = int(5e7)

    print('Looping...')
    for _ in range(fifty_million):
        pass

    print('Done looping!')
    return True

In [144]:
connect()
fifty_million_loops()

Connecting...
Connected!
"connect()" took 2.003 seconds to execute
Looping...
Done looping!
"fifty_million_loops()" took 1.412 seconds to execute


True

In [145]:
def test_connect():
    result = connect()
    assert result

def test_fifty_million_loops():
    result = fifty_million_loops()
    assert result

In [146]:
%%time
ipytest.run('-vv')

======================================= test session starts ========================================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.5.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content
plugins: typeguard-4.3.0, anyio-3.7.1
collecting ... collected 8 items

t_aa44b0edb0ff4fc18c0b1be2ef732725.py::test_add PASSED                                       [ 12%]
t_aa44b0edb0ff4fc18c0b1be2ef732725.py::test_passes PASSED                                    [ 25%]
t_aa44b0edb0ff4fc18c0b1be2ef732725.py::test_passes_without_info PASSED                       [ 37%]
t_aa44b0edb0ff4fc18c0b1be2ef732725.py::test_passes_but_should_not PASSED                     [ 50%]
t_aa44b0edb0ff4fc18c0b1be2ef732725.py::test_passes_but_bad_style PASSED                      [ 62%]
t_aa44b0edb0ff4fc18c0b1be2ef732725.py::test_fibonacci PASSED                                 [ 75%]
t_aa44b0edb0ff4fc18c0b1be2ef732725.py::test_connect PASSED                                   [ 87%]
t_aa

<ExitCode.OK: 0>

In [147]:
ar1 = np.arange(24).reshape(3, 4, 2)

# for row in ar1:
#   for element in row:
#     print(element)

#better iterator: https://numpy.org/doc/stable/reference/generated/numpy.nditer.html#
with np.nditer(ar1, op_flags=['readwrite']) as it:
  for x in it:
    x[...] = x ** 2

print(ar1)

[[[  0   1]
  [  4   9]
  [ 16  25]
  [ 36  49]]

 [[ 64  81]
  [100 121]
  [144 169]
  [196 225]]

 [[256 289]
  [324 361]
  [400 441]
  [484 529]]]


In [148]:
import numpy.ma as ma
import math

ls = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, np.nan, np.inf]
for_masking = np.array(ls)

print(for_masking.mean())

masked = ma.masked_array(for_masking, mask=[1 if math.isnan(e) or math.isinf(e) else 0 for e in ls]) #mask=[1] maskuje / mask=[0] nie maskuje
print(masked.mean())

print(masked)

nan
5.5
[1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 -- --]


In [149]:
original = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
view = original.view()
copy = original.copy()

print(original)
print(view)
print(copy)

view[0] = 100
copy[0] = 200

print(original)
print(view)
print(copy)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[100   2   3   4   5   6   7   8   9  10]
[100   2   3   4   5   6   7   8   9  10]
[200   2   3   4   5   6   7   8   9  10]


In [150]:
new_arr = original[[1,2,3]] #copy with indexing
print(new_arr)
new_arr[0] = 100
print(new_arr)
print(original)

[2 3 4]
[100   3   4]
[100   2   3   4   5   6   7   8   9  10]


In [151]:
print(original.base) #how to check copy or not
print(view.base)
print(copy.base)

None
[100   2   3   4   5   6   7   8   9  10]
None


In [152]:
custom_arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

def square_if_even(x: int) -> int:
  if x % 2 == 0:
    return x ** 2
  return x

vectorize_square_if_even = np.vectorize(square_if_even) #wektoryzacja funkcji

print(vectorize_square_if_even(custom_arr))

[[  1   4   3  16   5]
 [ 36   7  64   9 100]]


In [153]:
custom_data_type = np.dtype([('name', 'U100'), ('age', 'i4'), ('weight', 'f8')]) #https://numpy.org/doc/stable/reference/arrays.dtypes.html

In [154]:
dt = np.dtype(np.int32)

print(dt.name)
print(dt.type)
print(dt.byteorder)
print(dt.itemsize)

int32
<class 'numpy.int32'>
=
4


In [155]:
rra = np.array(['hellooooooo', 'world', 'how', 'are', 'you'], dtype='U6') #wymuszenie typu
print(rra.dtype)

<U6


In [156]:
dt = np.dtype("i4, (2,3)f8, f4")

In [157]:
%env

{'SHELL': '/bin/bash',
 'NV_LIBCUBLAS_VERSION': '12.2.5.6-1',
 'NVIDIA_VISIBLE_DEVICES': 'all',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'NV_NVML_DEV_VERSION': '12.2.140-1',
 'NV_CUDNN_PACKAGE_NAME': 'libcudnn8',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'NV_LIBNCCL_DEV_PACKAGE': 'libnccl-dev=2.19.3-1+cuda12.2',
 'NV_LIBNCCL_DEV_PACKAGE_VERSION': '2.19.3-1',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'HOSTNAME': '746af68f5f20',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'COLAB_TPU_1VM': '',
 'GCE_METADATA_TIMEOUT': '3',
 'NVIDIA_REQUIRE_CUDA': 'cuda>=12.2 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>

In [158]:
%env MY_ENV_VAR=hello

env: MY_ENV_VAR=hello


In [159]:
%env MY_ENV_VAR

'hello'

In [160]:
en = %env MY_ENV_VAR
print(en)

hello


In [161]:
%store custom_data_type

Stored 'custom_data_type' (VoidDType)


$\int \frac{1}{x} dx = \ln \left| x \right| + C$

In [162]:
%%HTML

<html>

<body>

<h1>Hello World</h1>

<p>Welcome to my website</p>

</body>

</html>