<a href="https://colab.research.google.com/github/JarekMaleszyk/data-science-project-sandbox/blob/main/numpy_advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [187]:
import numpy as np
import pandas as pd

In [188]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv')
df.reset_index(inplace=True)
df.head()

index  longitude  latitude  housing_median_age  total_rooms  \
0      0    -122.05     37.37                27.0       3885.0   
1      1    -118.30     34.26                43.0       1510.0   
2      2    -117.81     33.78                27.0       3589.0   
3      3    -118.36     33.82                28.0         67.0   
4      4    -119.67     36.33                19.0       1241.0   

   total_bedrooms  population  households  median_income  median_house_value  
0           661.0      1537.0       606.0         6.6085            344700.0  
1           310.0       809.0       277.0         3.5990            176500.0  
2           507.0      1484.0       495.0         5.7934            270500.0  
3            15.0        49.0        11.0         6.1359            330000.0  
4           244.0       850.0       237.0         2.9375             81700.0

In [189]:
df.at[2, "longitude"]

-117.81

In [190]:
df.iat[2, 1]

-117.81

In [191]:
a = np.random.random((5,6,7,1,2,3))
b = np.random.random((5,1,7,5,1,1))

In [192]:
print(a.shape)
print(b.shape)

(5, 6, 7, 1, 2, 3)
(5, 1, 7, 5, 1, 1)


In [193]:
c = a + b
c.shape

(5, 6, 7, 5, 2, 3)

In [194]:
try:
  a = np.random.random((5,6,7,1,2,3))
  b = np.random.random((5,2,7,5,1,1))
  print(a + b)
except ValueError:
  print(f"Operands could not be broadcast together with shapes {a.shape} {b.shape}")
except Exception as e:
  print(e)
else:
  pass
finally:
  pass

Operands could not be broadcast together with shapes (5, 6, 7, 1, 2, 3) (5, 2, 7, 5, 1, 1)


In [195]:
ma = np.array( [[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[11,12,13],
                [14,15,16],
                [17,18,19]]
                ])
print(ma.shape)
print(ma[0:2, 0:2, 0:1])

(2, 3, 3)
[[[ 1]
  [ 4]]

 [[11]
  [14]]]


In [196]:
print(ma[:, 0, 0, np.newaxis])
print(ma[np.newaxis, :, 0, 0])

[[ 1]
 [11]]
[[ 1 11]]


In [197]:
print(ma[:, [True, True, False]])

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [198]:
arr = np.arange(10, 300, 5.2, dtype=float)
np.random.shuffle(arr)
print(arr)

[119.2 150.4 233.6 244.  129.6  36.  197.2 238.8 155.6 134.8 290.8 166.
  82.8  51.6  77.6  30.8  15.2 108.8 202.4 285.6 124.4 275.2 218.  259.6
 270.  181.6 145.2 171.2  93.2 223.2 212.8 140.   98.4 254.4  56.8  67.2
 114.  176.4  10.   62.  280.4  20.4 186.8 103.6 228.4 296.  192.   41.2
  72.4 207.6 264.8 249.2  46.4 160.8  25.6  88. ]


In [199]:
# arr.sort()

In [200]:
print(np.argmin(arr))
print(np.argmax(arr))

38
45


In [201]:
zrr = np.zeros_like(arr)
print(zrr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]


In [202]:
arr.__getitem__(slice(0, 10, 2))

array([119.2, 233.6, 129.6, 197.2, 155.6])

In [203]:
try:
  np.where[arr > 88., arr, arr]
except TypeError:
  print("numpy._ArrayFunctionDispatcher' object is not subscriptable")
except Exception as e:
  print(e)
else:
  pass
finally:
  pass

numpy._ArrayFunctionDispatcher' object is not subscriptable


In [204]:
arr.shape

(56,)

In [205]:
arr[arr > 88]

array([119.2, 150.4, 233.6, 244. , 129.6, 197.2, 238.8, 155.6, 134.8,
       290.8, 166. , 108.8, 202.4, 285.6, 124.4, 275.2, 218. , 259.6,
       270. , 181.6, 145.2, 171.2,  93.2, 223.2, 212.8, 140. ,  98.4,
       254.4, 114. , 176.4, 280.4, 186.8, 103.6, 228.4, 296. , 192. ,
       207.6, 264.8, 249.2, 160.8])

In [206]:
!cat /var/log/bootstrap.log | grep adduser -A 4

2023-10-04 02:07:18 URL:http://ftpmaster.internal/ubuntu/pool/main/a/adduser/adduser_3.118ubuntu5_all.deb [155528/155528] -> "/build/chroot//var/cache/apt/archives/partial/adduser_3.118ubuntu5_all.deb" [1]
2023-10-04 02:07:20 URL:http://ftpmaster.internal/ubuntu/pool/main/a/apt/apt_2.4.5_amd64.deb [1379030/1379030] -> "/build/chroot//var/cache/apt/archives/partial/apt_2.4.5_amd64.deb" [1]
2023-10-04 02:07:20 URL:http://ftpmaster.internal/ubuntu/pool/main/b/base-files/base-files_12ubuntu4_amd64.deb [62940/62940] -> "/build/chroot//var/cache/apt/archives/partial/base-files_12ubuntu4_amd64.deb" [1]
2023-10-04 02:07:20 URL:http://ftpmaster.internal/ubuntu/pool/main/b/base-passwd/base-passwd_3.5.52build1_amd64.deb [49100/49100] -> "/build/chroot//var/cache/apt/archives/partial/base-passwd_3.5.52build1_amd64.deb" [1]
2023-10-04 02:07:21 URL:http://ftpmaster.internal/ubuntu/pool/main/b/bash/bash_5.1-6ubuntu1_amd64.deb [768660/768660] -> "/build/chroot//var/cache/apt/archives/partial/bash_5.1-

In [207]:
!pip install pytest ipytest --quiet

In [208]:
import ipytest
ipytest.autoconfig(clean=True) #https://pypi.org/project/ipytest/

In [209]:
def test_add():
  %time
  assert 1 + 1 == 2

In [210]:
import pytest

def test_passes():
    with pytest.raises(Exception) as e_info:
        x = 1 / 0

def test_passes_without_info():
    with pytest.raises(Exception):
        x = 1 / 0

# def test_fails():
#     with pytest.raises(Exception) as e_info:
#         x = 1 / 1

# def test_fails_without_info():
#     with pytest.raises(Exception):
#         x = 1 / 1

# Don't do this. Assertions are caught as exceptions.
def test_passes_but_should_not():
    try:
        x = 1 / 1
        assert False
    except Exception:
        assert True

# Even if the appropriate exception is caught, it is bad style,
# because the test result is less informative
# than it would be with pytest.raises(e)
# (it just says pass or fail.)

def test_passes_but_bad_style():
    try:
        x = 1 / 0
        assert False
    except ZeroDivisionError:
        assert True

# def test_fails_but_bad_style():
#     try:
#         x = 1 / 1
#         assert False
#     except ZeroDivisionError:
#         assert True

In [211]:
%%time
ipytest.run('-vv')

======================================= test session starts ========================================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.5.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content
plugins: typeguard-4.3.0, anyio-3.7.1
collecting ... collected 5 items

t_d1ab5275e1384d91b6b16fc099424f60.py::test_add PASSED                                       [ 20%]
t_d1ab5275e1384d91b6b16fc099424f60.py::test_passes PASSED                                    [ 40%]
t_d1ab5275e1384d91b6b16fc099424f60.py::test_passes_without_info PASSED                       [ 60%]
t_d1ab5275e1384d91b6b16fc099424f60.py::test_passes_but_should_not PASSED                     [ 80%]
t_d1ab5275e1384d91b6b16fc099424f60.py::test_passes_but_bad_style PASSED                      [100%]

======================================== 5 passed in 0.06s =========================================
CPU times: user 119 ms, sys: 10.7 ms, total: 130 ms
Wall time: 137 ms


<ExitCode.OK: 0>