<a href="https://colab.research.google.com/github/JarekMaleszyk/data-science-project-sandbox/blob/main/nympy_summary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np

list_a = [1,2,3,4,5,6]
len(list_a)

6

In [27]:
array_a = np.array([1,2,3,4,5,6])
len(list_a)
len(array_a)

6

In [28]:
array_a = np.array([1,2,3,4,5,6])
len(list_a)

6

In [29]:
array_b = np.array([[1,2,3],[4,5,6]])
len(array_b)

2

In [30]:
print(type(list_a))
print(type(array_a))
print(type(array_b))

<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [31]:
print(array_b)

[[1 2 3]
 [4 5 6]]


In [32]:
try:
  list_a.shape
except AttributeError:
  print("List: list_b has no shape")

List: list_b has no shape


In [33]:
array_b.shape

(2, 3)

In [34]:
list_c = list_a[0] + list_a[1]
print(list_c)
array_c = array_b[0] + array_b[1]
print(array_c)

3
[5 7 9]


In [35]:
array_b[1:, -1:]

array([[6]])

In [36]:
rn = np.random.randn(1)

rn

array([1.69016422])

In [37]:
d = np.arange('2002-10-27T04:30', 240, 60, dtype='M8[m]')
d


array(['2002-10-27T04:30', '2002-10-27T05:30', '2002-10-27T06:30',
       '2002-10-27T07:30'], dtype='datetime64[m]')

In [38]:
np.datetime_as_string(d, timezone='UTC')

array(['2002-10-27T04:30Z', '2002-10-27T05:30Z', '2002-10-27T06:30Z',
       '2002-10-27T07:30Z'], dtype='<U35')

In [39]:
import pytz
np.datetime_as_string(d, timezone=pytz.timezone('US/Eastern'))

array(['2002-10-27T00:30-0400', '2002-10-27T01:30-0400',
       '2002-10-27T01:30-0500', '2002-10-27T02:30-0500'], dtype='<U39')

In [45]:

array_a = np.array([1,2,3,4,5,6])
array_b = np.array([7,8,9,10,11,12])


array_c = np.array([array_a, array_b])
print(array_c)

array_c[0:1, 3:4] = 100 #górny zakres wycinania się nie liczy
print(array_c)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[  1   2   3 100   5   6]
 [  7   8   9  10  11  12]]


In [46]:
array_c[0:2, 3:5] = 100 #górny zakres wycinania się nie liczy
print(array_c)

[[  1   2   3 100 100   6]
 [  7   8   9 100 100  12]]


In [49]:
a = np.array([1,2,3,4,5,6])
b = a * np.array([2,0,2,0,2,0])
print(b)

[ 2  0  6  0 10  0]


In [52]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
y = np.array([1,0,1])

c = x + y #broadcasting

print(c)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [62]:
l1 = [1,2,3,4,5,6,4,3,2,0]
l2 = [7,8,9,4,11,12,3,5,0,0]
print("###################################")
print(l1 == l2)
print(l1 > l2)
print(l1 >= l2)
print(l1 < l2)
print(l1 != l2)

a1 = np.array(l1)
a2 = np.array(l2)
print("###################################")
print(a1 == a2)
print(a1 > a2)
print(a1 >= a2)
print(a1 < a2)
print(a1 != a2)
print("###################################flatnonzero")
print(np.flatnonzero(a1 == a2))
print(np.flatnonzero(a1 != a2))
print("###################################where")
print(np.where(a1 == a2))
print(np.where(a1 != a2))
print("###################################nonzero")
print(np.nonzero(a1 == a2))
print(np.nonzero(a1 != a2))

###################################
False
False
False
True
True
###################################
[False False False  True False False False False False  True]
[False False False False False False  True False  True False]
[False False False  True False False  True False  True  True]
[ True  True  True False  True  True False  True False False]
[ True  True  True False  True  True  True  True  True False]
###################################flatnonzero
[3 9]
[0 1 2 4 5 6 7 8]
###################################where
(array([3, 9]),)
(array([0, 1, 2, 4, 5, 6, 7, 8]),)
###################################nonzero
(array([3, 9]),)
(array([0, 1, 2, 4, 5, 6, 7, 8]),)


In [57]:
b = np.array([[1,2,3],[4,5,6],[4,3,2]])
bool_inx = b > 2
print(bool_inx)
print(b[bool_inx])
print(b[b > 2])

[[False False  True]
 [ True  True  True]
 [ True  True False]]
[3 4 5 6 4 3]
[3 4 5 6 4 3]


In [60]:
t = np.array([[1,2,3],[4,5,6],[4,3,2]])
bool_inx = ~(t > 2)
print(bool_inx)
print(t[bool_inx])
print(t[~(t > 2)])

[[ True  True False]
 [False False False]
 [False False  True]]
[1 2 2]
[1 2 2]


In [61]:
f = np.array([10,20,30,40,50,60])
i = f[[3,4,5]]
print(i)

[40 50 60]


In [65]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
print("###################################flatnonzero")
even_inxs1 = np.flatnonzero(numbers % 2 == 0)

print(even_inxs1)
even_numbers1 = numbers[even_inxs1]

print(even_numbers1)
print("###################################flatten")
even_inxs2 = np.argwhere(numbers % 2 == 0).flatten()

print(even_inxs2)
even_numbers2 = numbers[even_inxs2]

print(even_numbers2)

###################################flatnonzero
[1 3 5 7 9]
[ 2  4  6  8 10]
###################################flatten
[1 3 5 7 9]
[ 2  4  6  8 10]


In [71]:
scores = np.array([70, 40, 30, 20, 90, 110])
names = np.array(["Bob", "Liz", "Pat", "Robin", "George", "Jessie"])

inxs = np.argsort(scores) #sortowanie
print(inxs)
print(scores[inxs])
print(names[inxs])
inxs = inxs[::-1]
print(scores[inxs])
print(names[inxs])

[3 2 1 0 4 5]
[ 20  30  40  70  90 110]
['Robin' 'Pat' 'Liz' 'Bob' 'George' 'Jessie']
[110  90  70  40  30  20]
['Jessie' 'George' 'Bob' 'Liz' 'Pat' 'Robin']
