<a href="https://colab.research.google.com/github/JarekMaleszyk/data-science-project-sandbox/blob/main/nympy_summary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
list_a = [1,2,3,4,5,6]
len(list_a)

6

In [3]:
list_array_a = np.array([1,2,3,4,5,6])
len(list_a)
len(list_b)

2

In [4]:
import numpy as np

array_a = np.array([1,2,3,4,5,6])
len(list_a)

6

In [9]:
array_b = np.array([[1,2,3],[4,5,6]])
len(array_b)

2

In [11]:
print(type(list_a))
print(type(array_a))
print(type(list_b))
print(type(array_b))

<class 'list'>
<class 'numpy.ndarray'>
<class 'list'>
<class 'numpy.ndarray'>


In [13]:
print(list_b)
print(array_b)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [17]:
try:
  list_b.shape
except AttributeError:
  print("List: list_b has no shape")

List: list_b has no shape


In [15]:
array_b.shape

(2, 3)

In [19]:
list_c = list_b[0] + list_b[1]
print(list_c)
array_c = array_b[0] + array_b[1]
print(array_c)

[1, 2, 3, 4, 5, 6]
[5 7 9]
